### ISSUE TITLE
TO-DO (subject to change)

### ISSUE THREAD

**Issue by regfunkid** [regfunkid/More-Foods-Datapack#2]
- [x] Adding Snow Cones
- [x] Updating the Sandwich recipe and texture
- [x] Updating the Apple Pie and Apple Pie Slice textures
- [x] Fixing the Kabob System
- [x] Possibly porting the mod over to Forge and Quilt (HARD possibly)
  - I can't port to Forge until they release a version for 1.21, or at least 1.20.5. But Quilt is done now
- [x] Do this #11 
- [x] Add a Config menu

Please remember that I'm only 1 person! This is a big undertaking for me, even if the pack seems small. I'm doing what I can. (i'm also working a full time job lmao)
If you have more food ideas, shoot them my way!
